name: build-workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: install apt packages
      run: sudo apt update && sudo apt install gcc-multilib gcc grub-pc-bin xorriso nasm mtools -y
    - name: make
      run: make
